language: c
notifications: # set notification options
  slack:
    rooms:
      - ucsc-cgl:Edwfgt7MJEVZV9Lib3igueTF
    on_success: change
    on_failure: always
  email: false

sudo: required

before_install:
- sudo apt-get update -qq

os:
  - linux
#  - osx

install:
- sudo apt-get update
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
- wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
# We do this conditionally because it saves us some downloading if the
# version is the same.
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- which python
- python --version
- conda install pytest
- which python
- python --version
- python setup.py install

script:
- python setup.py test
